title: DOP HPC Cluster 

author: 
  name: GitHub User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.


titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Additional configuration for SEO tags
seo:
  title: High Peformance Computer Cluster Documentation
  description: Provides documentation of using DOP-HPC cluster for calculations. Provides introduction to do parallel programming with python using multiprocessing and mpi4py module.
  url: https://navmohan-24.github.io/HPC-Documentation/
  Github:
    username: NavMohan-24

theme: minima
minima: 
 skin: auto

  
markdown: GFM

