title: DOP HPC Cluster 
author: 
  name: GitHub User
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This site provides user documentation for the HPC cluster at the Department of Physics, Cochin University of Science and Technology. 
  It covers basic Linux commands, SLURM job management, and parallel programming using Python, enabling users to effectively utilize the cluster's resources.


titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Additional configuration for SEO tags
seo:
  title: High Peformance Computer Cluster Documentation
  description: Provides documentation of using DOP-HPC cluster for calculations. Provides introduction to do parallel programming with python using multiprocessing and mpi4py module.
  url: https://navmohan-24.github.io/HPC-Documentation/
  Github:
    username: NavMohan-24

theme: minima
minima: 
 skin: auto

  
markdown: GFM

